#!/bin/bash

export GIT_REF=`git show --pretty=format:%h --quiet`
export GIT_BRANCH=${TRAVIS_BRANCH:-`git rev-parse --abbrev-ref HEAD | tr -d '\n'`}

export TZ=":Europe/London" # UTC
export GIT_ISO_DATE=`git show --pretty=format:%cd --date=iso --quiet`
export PKG_DATE=`ruby -rdate -e 'puts Time.at(DateTime.parse(ENV["GIT_ISO_DATE"]).to_time.to_i).strftime("%Y_%m_%d.%H_%M")'`

set -e
set -v

ls -lah dist/* || true

MC_CMD="./mc"

if [[ "$OSTYPE" == "darwin"* ]]; then # MAC
  wget https://dl.minio.io/client/mc/release/darwin-amd64/mc
  chmod +x mc
elif [[ "$OSTYPE" == "linux-gnu" ]]; then # LINUX
  wget https://dl.minio.io/client/mc/release/linux-amd64/mc
  chmod +x mc
else
  wget https://dl.minio.io/client/mc/release/windows-amd64/mc.exe
  MC_CMD="./mc.exe"
fi

$MC_CMD --version
$MC_CMD config host add postbird https://paxa.kuber.host travis postbird --api s3v4

for filename in ./dist/*.{dmg,deb,rpm,snap,exe}; do
  [ -e "$filename" ] || continue
  $MC_CMD cp "$filename" postbird/postbird-builds/$PKG_DATE-$GIT_BRANCH-$GIT_REF/
done
