#!/bin/bash

export GIT_REF=`git show --pretty=format:%h --quiet`
export GIT_BRANCH=${TRAVIS_BRANCH:-`git rev-parse --abbrev-ref HEAD | tr -d '\n'`}
export PKG_DATE=`git show --pretty=format:%cd --date=short --quiet`

set -e
set -v

ls -lah dist/* || true

if [ "$(uname)" == "Darwin" ]; then
  brew install minio-mc
else
  wget https://dl.minio.io/client/mc/release/linux-amd64/mc
  chmod +x mc
  sudo mv mc /usr/bin/mc
fi

mc --version
mc config host add paxa https://paxa.kuber.host travis postbird --api s3v4

for filename in ./dist/*.{dmg,deb,rpm,nsis}; do
  [ -e "$filename" ] || continue
  mc cp $filename paxa/postbird-builds/$PKG_DATE-$GIT_BRANCH-$GIT_REF/
done
